#server:
#  port: 8180
#  servlet:
#    context-path: /hb-jw-user

spring:
  application:
    name: ros-demo
  # 打开日志颜色输出
  output:
    ansi:
      enabled: detect
#  profiles:
#    active: @profileActive@
#  # 两个war包同时在一个tomcat中运行会出问题的，必须添加一下参数设置
#  jmx:
#    enabled: false

#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.3.28:3306/hb_jw_user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
#    username: xing
#    password: 123456
#  cloud:
#    nacos:
#      discovery:
#        #指定nacos注册中心地址
#        server-addr: 127.0.0.1:8848
#
#  redis:
#    host: 127.0.0.1
#    timeout: 30000ms
#    password: huibo1206
#    port: 6379
#    database: 0
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 8 # 连接池中的最大空闲连接
#        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制)
#        min-idle: 0 # 连接池中的最小空闲连接
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5level [%15thread] %-50.50(%logger{39}.%method:%-3line) - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %yellow(%5level) [%15thread] %cyan(%-50.50(%logger{39}.%method:%-3line)) - %msg%n"
  file:
    name: ./logs/ros-demo/ros-demo.log
  level:
    com.github.xingshuangs.ros.demo.rosdemo: debug

